<a href="https://colab.research.google.com/github/therahulbhagat19/MLProjects/blob/main/breastCancerPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
ds = pd.read_csv('Breast_cancer_data.csv')
ds.head()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0
1,20.57,17.77,132.90,1326.0,0.08474,0
2,19.69,21.25,130.00,1203.0,0.10960,0
3,11.42,20.38,77.58,386.1,0.14250,0
4,20.29,14.34,135.10,1297.0,0.10030,0

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   mean_radius      569 non-null    float64
 1   mean_texture     569 non-null    float64
 2   mean_perimeter   569 non-null    float64
 3   mean_area        569 non-null    float64
 4   mean_smoothness  569 non-null    float64
 5   diagnosis        569 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 26.8 KB

In [ ]:
ds.corr()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
mean_radius,1.000000,0.323782,0.997855,0.987357,0.170581,-0.730029
mean_texture,0.323782,1.000000,0.329533,0.321086,-0.023389,-0.415185
mean_perimeter,0.997855,0.329533,1.000000,0.986507,0.207278,-0.742636
mean_area,0.987357,0.321086,0.986507,1.000000,0.177028,-0.708984
mean_smoothness,0.170581,-0.023389,0.207278,0.177028,1.000000,-0.358560
diagnosis,-0.730029,-0.415185,-0.742636,-0.708984,-0.358560,1.000000

In [ ]:
ds['diagnosis'].unique()

array([0, 1])

In [ ]:
x = ds.drop('diagnosis',axis=1)
x.head()

   mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
0        17.99         10.38          122.80     1001.0          0.11840
1        20.57         17.77          132.90     1326.0          0.08474
2        19.69         21.25          130.00     1203.0          0.10960
3        11.42         20.38           77.58      386.1          0.14250
4        20.29         14.34          135.10     1297.0          0.10030

In [ ]:
y= pd.DataFrame(ds['diagnosis'])
y.head()

   diagnosis
0          0
1          0
2          0
3          0
4          0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 3)

In [ ]:
x_train.head()

     mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
251        11.50         18.45           73.28      407.4          0.09345
550        10.86         21.48           68.51      360.5          0.07431
18         19.81         22.15          130.00     1260.0          0.09831
319        12.43         17.00           78.60      477.3          0.07557
415        11.89         21.17           76.39      433.8          0.09773

In [ ]:
y_train.head()

     diagnosis
251          1
550          1
18           0
319          1
415          1

In [ ]:
x2 = ds.drop(['mean_perimeter',	'mean_area'],axis=1)
x2.head()

   mean_radius  mean_texture  mean_smoothness  diagnosis
0        17.99         10.38          0.11840          0
1        20.57         17.77          0.08474          0
2        19.69         21.25          0.10960          0
3        11.42         20.38          0.14250          0
4        20.29         14.34          0.10030          0

In [ ]:
x2_train,x2_test,y2_train,y2_test = train_test_split(x2,y,random_state=3)
x2_train.head()

     mean_radius  mean_texture  mean_smoothness  diagnosis
251        11.50         18.45          0.09345          1
550        10.86         21.48          0.07431          1
18         19.81         22.15          0.09831          0
319        12.43         17.00          0.07557          1
415        11.89         21.17          0.09773          1

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
scaler1.fit_transform(x_train)
scaler2= StandardScaler()
scaler2.fit_transform(x2_train)
x_train.head()

     mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
251        11.50         18.45           73.28      407.4          0.09345
550        10.86         21.48           68.51      360.5          0.07431
18         19.81         22.15          130.00     1260.0          0.09831
319        12.43         17.00           78.60      477.3          0.07557
415        11.89         21.17           76.39      433.8          0.09773

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=25,criterion='entropy')
clf.fit(scaler1.fit_transform(x_train),np.array(y_train).ravel())
y_pred = clf.predict(scaler1.fit_transform(x_test))

In [ ]:
from sklearn.metrics import confusion_matrix
c1 = confusion_matrix(y_test,y_pred)

In [ ]:
clf2 = RandomForestClassifier(n_estimators=25,criterion='entropy')
clf2.fit(scaler2.fit_transform(x2_train),np.array(y2_train).ravel())
y2_pred = clf2.predict(scaler2.fit_transform(x2_test))

In [ ]:
c2 = confusion_matrix(y2_test,y2_pred)

In [ ]:
c1

array([[48,  5],
       [ 6, 84]])

In [ ]:
c2

array([[53,  0],
       [ 0, 90]])